### ISSUE TITLE
Give me little more guide before making PR

### ISSUE THREAD

**Issue by sshojiro** [usnistgov/pyMCR#6]
I have attempted to make a PR https://github.com/CCampJr/pyMCR/pull/5.
However, as you can see, codecov shows some errors. Could you give me little instruction to fix this?

Sorry to disturb you.

**Comment by CCampJr** [comment]
@sshojiro 

Thank you very much for your hard work!
* Make the PR to the 0.3.X branch since that's what you forked from
* In general, I try to avoid using sklearn as this adds a requirement for it to be installed for future users. PCA, for example, can be calculated using SVD from numpy.linalg.svd
* In the demo, for example, avoid using words like "outstanding" or "great" -- we want to be as objective as possible.
* Please move the two metrics into a new python file called rank.py as these are effectively rank-finding methods. I intend for metric.py to only contain error function metrics that can be used by MCR for minimization.

Thank you very, very much for your contribution. I look forward to downloading your code and testing it out.

**Comment by sshojiro** [comment]
@CCampJr 
I also appreciate your great contribution so much. I've been thinking to start some research projects involving MCR-ALS. So, this repository will be a great help.

Thank you for your comments. After fixing your feedbacks, I'll make a PR again.

Well, as for the second comment,
> In general, I try to avoid using sklearn as this adds a requirement for it to be installed for future users. PCA, for example, can be calculated using SVD from numpy.linalg.svd

I think you should add this description to `CONTRIBUTING.rst`. Hope that you will do so when you have time. Thank you in advance.

**Comment by CCampJr** [comment]
@sshojiro 

Good point: I will add a note to avoid external libraries unless absolutely necessary to the contributing guide-- thanks!

**Comment by CCampJr** [comment]
Just added a statement to CONTRIBUTING.rst

**Comment by CCampJr** [comment]
Thanks for the PR-- closing this issue
